### ISSUE TITLE
TurboWriter tool missed

### ISSUE THREAD

**Issue by lightelf76** [OpenNuvoton/N32926_NonOS_BSP#1]
There is PDF with tool description within BSP/Doc, but tool itself absent. There is version for N9H26, but not sure it compatible

**Comment by kchuang1** [comment]
The TurboWriter tool is under Tools/PC_Tools folder.

**Comment by lightelf76** [comment]
Excuse me, but I see no Tools folder for n32926 MPU. Can you post a link to mentioned folder? 
There is Tools/PC_Tools for N9H26, but I am not sure is it compatible with n32926 and there is no INI file for n32926 chip.

**Comment by kchuang1** [comment]
The turboWriter for N32926 and N32905 is compatible. The Non-OS Tool is created under N32905 to contain the TurboWriter tool. Please note that the tool for N329xY where Y represent 1,3,5,6 must match your device.

**Comment by lightelf76** [comment]
Thanks!
Any chance for source code release?

**Comment by kchuang1** [comment]
No source code changed for this tool.
